export const FEATURES = [
  {
    id: 'reversal',
    label: 'Reversal Scanner',
    icon: '🔄',
    status: 'live',
    description: 'Multi-factor reversal signal engine.',
    subOptions: [
      { id: 'analyze',   label: '🔍 Single Stock', icon: '🔍', path: '/reversal/analyze' },
      { id: 'sectors',   label: '🗂 Sector Scan',  icon: '🗂', path: '/reversal/sectors' },
      { id: 'watchlist', label: '📋 Watchlist',    icon: '📋', path: '/reversal/watchlist' },
      { id: 'macro',     label: '🌍 Macro View',   icon: '🌍', path: '/reversal/macro' },
    ],
  },
  {
    id: 'options',
    label: 'Options Analysis',
    icon: '📋',
    status: 'live',
    description: 'Live options chain, Greeks, IV skew, unusual activity.',
    subOptions: [
      { id: 'overview', label: '🏠 Overview',        icon: '🏠', path: '/options/overview' },
      { id: 'chain',    label: '⛓ Chain',            icon: '⛓', path: '/options/chain' },
      { id: 'unusual',  label: '🚨 Unusual Activity', icon: '🚨', path: '/options/unusual' },
      { id: 'skew',     label: '📐 IV Skew',          icon: '📐', path: '/options/skew' },
    ],
  },
  {
    id: 'earnings',
    label: 'Earnings Calendar',
    icon: '📅',
    status: 'live',
    description: 'Upcoming earnings with expected moves and EPS history.',
    subOptions: [
      { id: 'calendar', label: '📅 Calendar',         icon: '📅', path: '/earnings/calendar' },
      { id: 'analysis', label: '📊 Earnings Analysis', icon: '📊', path: '/earnings/analysis' },
    ],
  },
  {
    id: 'technical',
    label: 'Technical Analysis',
    icon: '📈',
    status: 'live',
    description: 'Chart patterns, support/resistance levels, momentum signals, and screener.',
    subOptions: [
      { id: 'indicators', label: '📊 Indicators',         icon: '📊', path: '/technical/indicators' },
      { id: 'patterns',   label: '🔍 Chart Patterns',     icon: '🔍', path: '/technical/patterns' },
      { id: 'levels',     label: '📏 Support/Resistance', icon: '📏', path: '/technical/levels' },
      { id: 'screener',   label: '🔎 Screener',           icon: '🔎', path: '/technical/screener' },
    ],
  },
  {
    id: 'fundamental',
    label: 'Fundamental Analysis',
    icon: '🏦',
    status: 'live',
    description: 'Valuation ratios, growth scores, financial health, and fundamental screener.',
    subOptions: [
      { id: 'valuation', label: '💹 Valuation',     icon: '💹', path: '/fundamental/valuation' },
      { id: 'growth',    label: '📈 Growth Score',  icon: '📈', path: '/fundamental/growth' },
      { id: 'health',    label: '🏥 Quality Score', icon: '🏥', path: '/fundamental/health' },
      { id: 'screener',  label: '🔎 Screener',      icon: '🔎', path: '/fundamental/screener' },
    ],
  },
  {
    id: 'sentiment',
    label: 'Market Sentiment',
    icon: '🧠',
    status: 'live',
    description: 'Fear & Greed index built from VIX, momentum, PCR, safe haven demand, junk bonds, breadth, and price strength.',
    subOptions: [
      { id: 'dashboard', label: '🧠 Dashboard', icon: '🧠', path: '/sentiment/dashboard' },
    ],
  },
  {
    id: 'insider',
    label: 'Insider Tracker',
    icon: '👁',
    status: 'live',
    description: 'SEC Form 4 insider buying and selling — open market purchases and cluster signals.',
    subOptions: [
      { id: 'feed',    label: '📋 Transaction Feed', icon: '📋', path: '/insider/feed' },
      { id: 'cluster', label: '🎯 Cluster Buys',     icon: '🎯', path: '/insider/cluster' },
    ],
  },
  {
    id: 'smart_money',
    label: 'Smart Money Scanner',
    icon: '💰',
    status: 'live',
    description: 'Top 50 stocks ranked by options flow, insider buying, and institutional positioning.',
    subOptions: [
      { id: 'scanner', label: '🔍 Scanner', icon: '🔍', path: '/smart_money/scanner' },
    ],
  },
  {
    id: 'ai_agent',
    label: 'AI Research Agent',
    icon: '🤖',
    status: 'live',
    description: 'AI-powered market research — ticker summaries, deep analysis, and interactive research chat.',
    subOptions: [
      { id: 'summary',  label: '📝 AI Summary',    icon: '📝', path: '/ai_agent/summary' },
      { id: 'research', label: '🔬 Deep Research',  icon: '🔬', path: '/ai_agent/research' },
      { id: 'chat',     label: '💬 Research Chat',  icon: '💬', path: '/ai_agent/chat' },
    ],
  },
]
